CREATE TABLE `ridiImpact` (
	`id` int AUTO_INCREMENT NOT NULL,
	`programRef` varchar(32) NOT NULL,
	`programName` varchar(256) NOT NULL,
	`programType` enum('Digital Skills','Entrepreneurship Training','Climate Education','Robotics','Community Partnership') NOT NULL,
	`location` varchar(256) NOT NULL,
	`communityPartner` varchar(256),
	`startDate` timestamp NOT NULL,
	`endDate` timestamp,
	`status` enum('Planning','Active','Completed','On Hold') NOT NULL DEFAULT 'Planning',
	`totalBeneficiaries` int NOT NULL DEFAULT 0,
	`women` int NOT NULL DEFAULT 0,
	`youth` int NOT NULL DEFAULT 0,
	`men` int NOT NULL DEFAULT 0,
	`referralsToHamzury` int NOT NULL DEFAULT 0,
	`impactStory` text,
	`notes` text,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `ridiImpact_id` PRIMARY KEY(`id`),
	CONSTRAINT `ridiImpact_programRef_unique` UNIQUE(`programRef`)
);
--> statement-breakpoint
CREATE TABLE `weeklyReports` (
	`id` int AUTO_INCREMENT NOT NULL,
	`reportRef` varchar(32) NOT NULL,
	`submittedByStaffId` varchar(32) NOT NULL,
	`submittedByName` varchar(256) NOT NULL,
	`weekEnding` timestamp NOT NULL,
	`goingWell1` text NOT NULL,
	`goingWell2` text NOT NULL,
	`goingWell3` text NOT NULL,
	`toWatch1` text NOT NULL,
	`toWatch2` text NOT NULL,
	`toWatch3` text NOT NULL,
	`keyInfo` text NOT NULL,
	`revenueThisWeek` int NOT NULL DEFAULT 0,
	`newClients` int NOT NULL DEFAULT 0,
	`activeTasks` int NOT NULL DEFAULT 0,
	`overdueTasks` int NOT NULL DEFAULT 0,
	`staffPresent` int NOT NULL DEFAULT 0,
	`staffTotal` int NOT NULL DEFAULT 0,
	`pendingApprovals` int NOT NULL DEFAULT 0,
	`isReadByFounder` boolean NOT NULL DEFAULT false,
	`readAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `weeklyReports_id` PRIMARY KEY(`id`),
	CONSTRAINT `weeklyReports_reportRef_unique` UNIQUE(`reportRef`)
);
