CREATE TABLE `affiliate_league_table` (
	`id` int AUTO_INCREMENT NOT NULL,
	`affiliateId` int NOT NULL,
	`affiliateCode` varchar(50) NOT NULL,
	`affiliateName` varchar(255) NOT NULL,
	`position` int NOT NULL,
	`leagueTier` enum('elite','premier','standard','entry','waiting') NOT NULL DEFAULT 'waiting',
	`totalConversions` int DEFAULT 0,
	`totalRevenue` decimal(12,2) DEFAULT '0',
	`totalEarnings` decimal(12,2) DEFAULT '0',
	`qualityScore` int DEFAULT 0,
	`contentBonusTotal` decimal(12,2) DEFAULT '0',
	`quarter` varchar(10) NOT NULL,
	`isActive` boolean NOT NULL DEFAULT true,
	`lastActivityAt` timestamp,
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	`updatedAt` timestamp NOT NULL DEFAULT (now()) ON UPDATE CURRENT_TIMESTAMP,
	CONSTRAINT `affiliate_league_table_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `ai_fund_log` (
	`id` int AUTO_INCREMENT NOT NULL,
	`allocationId` int,
	`amount` decimal(12,2) NOT NULL,
	`source` varchar(50) NOT NULL,
	`description` text,
	`balance` decimal(12,2),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `ai_fund_log_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `allocations` (
	`id` int AUTO_INCREMENT NOT NULL,
	`transactionRef` varchar(50) NOT NULL,
	`clientRef` varchar(50),
	`clientName` varchar(255),
	`service` varchar(255),
	`department` varchar(50),
	`totalAmount` decimal(12,2) NOT NULL,
	`institutionalAmount` decimal(12,2) NOT NULL,
	`opsAmount` decimal(12,2),
	`growthAmount` decimal(12,2),
	`aiFundAmount` decimal(12,2),
	`reserveAmount` decimal(12,2),
	`staffPoolAmount` decimal(12,2) NOT NULL,
	`aiStaffShare` decimal(12,2) DEFAULT '0',
	`humanStaffAmount` decimal(12,2),
	`staffPayouts` json,
	`affiliatePoolAmount` decimal(12,2) NOT NULL,
	`affiliateId` int,
	`affiliateCode` varchar(50),
	`affiliateTier` varchar(20),
	`affiliateCommission` decimal(12,2) DEFAULT '0',
	`contentBonus` decimal(12,2) DEFAULT '0',
	`affiliateTotalPayout` decimal(12,2) DEFAULT '0',
	`aiContributionPct` int DEFAULT 0,
	`quarter` varchar(10),
	`allocationStatus` enum('pending','approved','paid') NOT NULL DEFAULT 'pending',
	`approvedBy` varchar(255),
	`allocatedAt` timestamp NOT NULL DEFAULT (now()),
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `allocations_id` PRIMARY KEY(`id`)
);
--> statement-breakpoint
CREATE TABLE `skills_calendar` (
	`id` int AUTO_INCREMENT NOT NULL,
	`quarter` varchar(10) NOT NULL,
	`theme` varchar(100),
	`registrationStart` varchar(20) NOT NULL,
	`registrationEnd` varchar(20) NOT NULL,
	`orientationDate` varchar(20) NOT NULL,
	`classesStart` varchar(20) NOT NULL,
	`classesEnd` varchar(20) NOT NULL,
	`graduationDate` varchar(20) NOT NULL,
	`supportWindowStart` varchar(20),
	`supportWindowEnd` varchar(20),
	`executiveCircleStart` varchar(20),
	`executiveCircleEnd` varchar(20),
	`track1Name` varchar(255),
	`track1Time` varchar(50) DEFAULT '8:00 AM – 10:00 AM',
	`track2Name` varchar(255),
	`track2Time` varchar(50) DEFAULT '10:30 AM – 12:30 PM',
	`track3Name` varchar(255),
	`track3Time` varchar(50) DEFAULT '1:30 PM – 3:30 PM',
	`roboticsName` varchar(255) DEFAULT 'Robotics & Creative Tech Lab',
	`roboticsTime` varchar(50) DEFAULT '10:00 AM – 1:00 PM',
	`roboticsDays` varchar(50) DEFAULT 'Thursday–Friday',
	`calendarStatus` enum('upcoming','registration','active','support','completed') NOT NULL DEFAULT 'upcoming',
	`createdAt` timestamp NOT NULL DEFAULT (now()),
	CONSTRAINT `skills_calendar_id` PRIMARY KEY(`id`)
);
